openapi: 3.0.0
info:
  title: FM Comment Api
  description: YBC
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Scodus
    url: https://scodus.com
    email: scodusnp@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: http://{{url}}
tags:
  - name: comment
  - name: reply
paths:
  /api/comment:
    post:
      tags:
        - comment
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                employee_id:
                  type: string
                  example: ldjawldj
                commentable_type:
                  type: string
                  example: Post
                commentable_id:
                  type: integer
                  example: '1'
                comment:
                  type: string
                  example: Hello World
                description:
                  type: string
                  description: nullable
                  example: Your description here
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/comment/{comment_id}:
    post:
      tags:
        - comment
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                comment:
                  type: string
                  example: Hello Worldadw
                _method:
                  type: string
                  example: put
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: comment_id
          in: path
          schema:
            type: string
          required: true
          example: 67038027-8905-4f2e-bde6-f4c258de11df
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - comment
      summary: delete
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: comment_id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - comment
      summary: show
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: comment_id
          in: path
          schema:
            type: integer
          required: true
          example: '4'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/comment/{commentable_type}/{commentable_id}/all:
    get:
      tags:
        - comment
      summary: index
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: commentable_type
          in: path
          schema:
            type: string
          required: true
          example: Post
        - name: commentable_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/comment/{comment_id}/restore:
    get:
      tags:
        - comment
      summary: restore
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: comment_id
          in: path
          schema:
            type: integer
          required: true
          example: '4'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/reply:
    post:
      tags:
        - reply
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                employee_id:
                  type: string
                  example: ldjawldj
                comment:
                  type: string
                  example: Hello World
                comment_id:
                  type: integer
                  example: '4'
                description:
                  type: string
                  description: nullable
                  example: Your description here
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/reply/{reply_id}:
    get:
      tags:
        - reply
      summary: show
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: reply_id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - reply
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                comment:
                  type: string
                  example: Hello Worldadw
                _method:
                  type: string
                  example: put
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: reply_id
          in: path
          schema:
            type: integer
          required: true
          example: '5'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - reply
      summary: delete
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: reply_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/reply/{reply_id}/restore:
    get:
      tags:
        - reply
      summary: restore
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: reply_id
          in: path
          schema:
            type: integer
          required: true
          example: '4'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
