openapi: 3.0.0
info:
  title: FM Comment Api
  description: YBC
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Scodus
    url: https://scodus.com
    email: scodusnp@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: http://{{url}}
tags:
  - name: comment
  - name: reply
paths:
  /api/comment:
    post:
      tags:
        - comment
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                employee_id:
                  type: integer
                  example: '1'
                commentable_type:
                  type: string
                  example: Post
                commentable_id:
                  type: integer
                  example: '1'
                comment:
                  type: string
                  example: Hello World
                description:
                  type: string
                  description: nullable
                  example: Your description here
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/unread-comment-count:
    post:
      tags:
        - comment
      summary: get unread comment count
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                employee_id: 3
                commentables:
                  - commentable_type: Post
                    commentable_id: '1'
                  - commentable_type: Post
                    commentable_id: '2'
                  - commentable_type: Blog
                    commentable_id: '1'
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/comment/{comment_id}:
    post:
      tags:
        - comment
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                comment:
                  type: string
                  example: Hello Worldadw
                _method:
                  type: string
                  example: put
                description:
                  type: string
                  example: This is a description
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: comment_id
          in: path
          schema:
            type: string
          required: true
          example: 370b9840-29a9-475b-84b8-554360856ce5
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - comment
      summary: delete
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: comment_id
          in: path
          schema:
            type: string
          required: true
          example: 370b9840-29a9-475b-84b8-554360856ce5
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - comment
      summary: show
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: comment_id
          in: path
          schema:
            type: string
          required: true
          example: 370b9840-29a9-475b-84b8-554360856ce5
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/comment/{commentable_type}/{commentable_id}/all:
    get:
      tags:
        - comment
      summary: index
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: employee_id
          in: query
          schema:
            type: integer
          example: '3'
        - name: commentable_type
          in: path
          schema:
            type: string
          required: true
          example: Post
        - name: commentable_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/comment/{comment_id}/restore:
    get:
      tags:
        - comment
      summary: restore
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: comment_id
          in: path
          schema:
            type: string
          required: true
          example: 370b9840-29a9-475b-84b8-554360856ce5
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/reply:
    post:
      tags:
        - reply
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                employee_id:
                  type: string
                  example: ldjawldj
                comment:
                  type: string
                  example: Hello World
                comment_id:
                  type: string
                  example: dddc5777-cbee-4cd9-aea9-2a1e188c67d2
                description:
                  type: string
                  description: nullable
                  example: Your description here
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/reply/{reply_id}:
    get:
      tags:
        - reply
      summary: show
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: reply_id
          in: path
          schema:
            type: string
          required: true
          example: 08166dd4-8555-41c6-90d8-63d04ca0e57c
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - reply
      summary: update
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                comment:
                  type: string
                  example: Hello Worldadw
                _method:
                  type: string
                  example: put
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: reply_id
          in: path
          schema:
            type: string
          required: true
          example: 08166dd4-8555-41c6-90d8-63d04ca0e57c
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - reply
      summary: delete
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: reply_id
          in: path
          schema:
            type: string
          required: true
          example: 08166dd4-8555-41c6-90d8-63d04ca0e57c
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/reply/{reply_id}/restore:
    get:
      tags:
        - reply
      summary: restore
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: reply_id
          in: path
          schema:
            type: string
          required: true
          example: 08166dd4-8555-41c6-90d8-63d04ca0e57c
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
